name: mdl
summary: Markdown lint tool
description: |
  A tool to check markdown files and flag style issues.
  Usage: mdl file or cat file | mdl
grade: stable
confinement: strict
adopt-info: mdl
base: core18

apps:
  mdl:
    command: bin/mdl
    plugs: [home, removable-media]
    environment:
      LANG: C.UTF-8

parts:
  mdl:
    source: https://github.com/markdownlint/markdownlint.git
    plugin: ruby
    ruby-version: '3.0.2'
    override-pull: |
      snapcraftctl pull

      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info mdl | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | tr -d 'v')"
    override-build: |
      snapcraftctl build

      gem build mdl.gemspec
      gem install mdl-*.gem --env-shebang
